package ports.usecases.calendarUseCases.toggleMiscellaneousUseCase;

public interface ToggleMiscellaneousOutputBoundary {
    ToggleMiscellaneousResponseModel prepareSuccessView(ToggleMiscellaneousRequestModel toggleMiscellaneousRequestModel);
}
